services:
  chanclol:
    build: .
    image: ${IMAGE:-chanclol:latest}
    restart: unless-stopped
    container_name: chanclol
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data
